import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";

const SegoeUI = localFont({
  src: [
    {
      path: "./fonts/SegoeUI.ttf",
      weight: "400",
      style: "normal",
    },
    {
      path: "./fonts/SegoeUIBold.ttf",
      weight: "700",
      style: "bold",
    },
    {
      path: "./fonts/SegoeUIItalic.ttf",
      weight: "400",
      style: "italic",
    },
    {
      path: "./fonts/SegoeUIBoldItalic.ttf",
      weight: "700",
      style: "bold italic",
    },
  ],
  variable: "--font-segoe-ui",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${SegoeUI.variable} bg-[#010101]`}
      >
        {children}
      </body>
    </html>
  );
}
